"use client";

import React, { useEffect, useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { alertService } from "@/services/alertService";
import { DataStateView } from "@/components/ui/DataStateView";
import { Bell, ShieldAlert, CheckCircle2, Clock, Filter, AlertTriangle } from "lucide-react";
import type { HealthAlert } from "@/types/alert";

export default function AlertsPage() {
  const { user } = useAuth();
  const [alerts, setAlerts] = useState<HealthAlert[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState<"ALL" | "ACTIVE" | "RESOLVED">("ALL");

  useEffect(() => {
    if (!user?.uid) return;
    const unsubscribe = alertService.subscribeToAlerts(user.uid, (data) => {
      setAlerts(data);
      setLoading(false);
    });
    return () => unsubscribe();
  }, [user?.uid]);

  const filteredAlerts = alerts.filter((a) => {
    if (filter === "ACTIVE") return a.status === "ACTIVE";
    if (filter === "RESOLVED") return a.status === "RESOLVED";
    return true;
  });

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "var(--space-6)" }}>
      {/* Header */}
      <div
        style={{
          backgroundColor: "#FFFFFF",
          borderRadius: "var(--radius-xl)",
          border: "1px solid var(--border-subtle)",
          padding: "var(--space-6) var(--space-8)",
          boxShadow: "var(--shadow-sm)",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        <div>
          <h1 style={{ fontSize: "1.75rem", fontWeight: 750, color: "#0F172A" }}>
            Alerts & Health Events
          </h1>
          <p style={{ fontSize: "0.88rem", color: "var(--text-secondary)", marginTop: "2px" }}>
            Real-time notifications generated by the Samadhan Edge risk evaluation engine.
          </p>
        </div>

        {/* Filter Pills */}
        <div style={{ display: "flex", gap: "6px", backgroundColor: "#F1F5F9", padding: "4px", borderRadius: "var(--radius-pill)" }}>
          {(["ALL", "ACTIVE", "RESOLVED"] as const).map((f) => (
            <button
              key={f}
              type="button"
              onClick={() => setFilter(f)}
              style={{
                padding: "6px 14px",
                borderRadius: "var(--radius-pill)",
                fontSize: "0.82rem",
                fontWeight: filter === f ? 650 : 500,
                backgroundColor: filter === f ? "#FFFFFF" : "transparent",
                color: filter === f ? "#0F172A" : "#64748B",
                border: "none",
                cursor: "pointer",
              }}
            >
              {f === "ALL" ? "All Events" : f === "ACTIVE" ? "Active" : "Resolved"}
            </button>
          ))}
        </div>
      </div>

      {loading ? (
        <DataStateView status="LOADING" title="Retrieving alert records..." />
      ) : filteredAlerts.length === 0 ? (
        /* ZERO FAKE ALERTS: Honest empty state */
        <div
          style={{
            backgroundColor: "#FFFFFF",
            borderRadius: "var(--radius-xl)",
            border: "1px solid var(--border-subtle)",
            padding: "var(--space-12) var(--space-6)",
            boxShadow: "var(--shadow-sm)",
          }}
        >
          <div style={{ textAlign: "center", maxWidth: "460px", margin: "0 auto" }}>
            <div
              style={{
                width: "52px",
                height: "52px",
                borderRadius: "50%",
                backgroundColor: "#F0FDFA",
                border: "1px solid #B2DFDB",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                margin: "0 auto var(--space-4)",
                color: "#00695C",
              }}
            >
              <CheckCircle2 size={26} />
            </div>
            <h3 style={{ fontSize: "1.1rem", fontWeight: 700, color: "#0F172A", marginBottom: "var(--space-2)" }}>
              No alerts have been generated.
            </h3>
            <p style={{ fontSize: "0.88rem", color: "var(--text-secondary)", lineHeight: 1.55 }}>
              Your physiological signals and environmental sensor readings are currently operating within your established circadian baseline margins.
            </p>
          </div>
        </div>
      ) : (
        /* Real Alert Feed */
        <div style={{ display: "flex", flexDirection: "column", gap: "10px" }}>
          {filteredAlerts.map((alt) => {
            const isCritical = alt.severity === "CRITICAL" || alt.severity === "EMERGENCY";
            const isWarning = alt.severity === "WARNING";
            const bg = isCritical ? "#FEF2F2" : isWarning ? "#FFFBEB" : "#F8FAFC";
            const border = isCritical ? "#FECACA" : isWarning ? "#FDE68A" : "var(--border-subtle)";
            const titleColor = isCritical ? "#991B1B" : isWarning ? "#92400E" : "#0F172A";

            return (
              <div
                key={alt.id}
                style={{
                  backgroundColor: bg,
                  border: `1px solid ${border}`,
                  borderRadius: "var(--radius-lg)",
                  padding: "var(--space-6)",
                  display: "flex",
                  justifyContent: "space-between",
                  alignItems: "flex-start",
                  gap: "16px",
                  flexWrap: "wrap",
                }}
              >
                <div style={{ display: "flex", gap: "14px", alignItems: "flex-start" }}>
                  <div style={{ marginTop: "2px" }}>
                    <AlertTriangle size={20} color={isCritical ? "#B91C1C" : isWarning ? "#B45309" : "#00695C"} />
                  </div>
                  <div>
                    <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
                      <span
                        style={{
                          fontSize: "0.7rem",
                          fontWeight: 700,
                          padding: "2px 7px",
                          borderRadius: "var(--radius-pill)",
                          backgroundColor: "#FFFFFF",
                          color: titleColor,
                          border: `1px solid ${border}`,
                          fontFamily: "var(--font-mono)",
                        }}
                      >
                        {alt.severity}
                      </span>
                      <span style={{ fontSize: "0.72rem", color: "#64748B", textTransform: "uppercase" }}>
                        SOURCE: {alt.source}
                      </span>
                    </div>

                    <h3 style={{ fontSize: "1.05rem", fontWeight: 700, color: titleColor, marginBottom: "4px" }}>
                      {alt.title}
                    </h3>
                    <p style={{ fontSize: "0.88rem", color: "#334155", lineHeight: 1.5, maxWidth: "65ch" }}>
                      {alt.description}
                    </p>
                    {alt.relevantValue && (
                      <div style={{ fontSize: "0.8rem", color: "#475569", marginTop: "6px" }}>
                        Telemetry Value: <strong>{alt.relevantValue}</strong>
                      </div>
                    )}
                  </div>
                </div>

                <div style={{ textAlign: "right", fontSize: "0.78rem", color: "#64748B", fontFamily: "var(--font-mono)" }}>
                  <div>{new Date(alt.timestamp).toLocaleString()}</div>
                  <div style={{ marginTop: "6px" }}>
                    Status: <strong style={{ color: alt.status === "ACTIVE" ? "#B91C1C" : "#00695C" }}>{alt.status}</strong>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
