/**
 * Samadhan Health LLM Service & Modal Adapter
 * 
 * SERVER-SIDE ONLY. Never import or call from client components.
 * 
 * Responsibilities:
 * 1. Isolated adapter between SamadhanHealthContext and deployed Modal LLM endpoint.
 * 2. Authenticates via server-side SAMADHAN_LLM_API_KEY (never exposed to client).
 * 3. Enforces bounded 8-second request timeout and at most 1 transient retry.
 * 4. Strictly validates structured output (explanation, guidance, urgency, disclaimer).
 * 5. Guarantees deterministic risk and fall state immutability.
 * 6. Graceful degradation: returns AI_ASSISTANT_UNAVAILABLE if Modal is offline.
 * 7. Sanitized operational logging (no API keys, no tokens, no PHI in logs).
 */

import type {
  SamadhanHealthContext,
  SamadhanLlmResponse,
  LlmUrgency,
  ModalRawResponse,
} from "@/types/llm";

const DEFAULT_MODAL_URL = "https://prasadaditya666--samadhan-health-api-api-endpoint.modal.run";
const REQUEST_TIMEOUT_MS = 35000;
const MAX_EXPLANATION_LENGTH = 2000;
const MAX_GUIDANCE_ITEMS = 6;
const MAX_GUIDANCE_ITEM_LENGTH = 300;
const STANDARD_DISCLAIMER =
  "Non-diagnostic clinical explanation generated by AI. Sensor telemetry and risk indicators are algorithmic estimates. Seek professional medical care for health emergencies.";

export class SamadhanLlmService {
  private apiUrl: string;
  private apiKey: string;

  constructor() {
    this.apiUrl = process.env.SAMADHAN_LLM_API_URL || DEFAULT_MODAL_URL;
    this.apiKey = process.env.SAMADHAN_LLM_API_KEY || "";
  }

  /**
   * Safe Fallback Response when Modal is offline, times out, or returns malformed output.
   * Preserves authoritative health state.
   */
  private createFallbackResponse(
    context: SamadhanHealthContext,
    reason: string,
    latencyMs: number = 0
  ): SamadhanLlmResponse {
    return {
      status: "AI_ASSISTANT_UNAVAILABLE",
      explanation: "",
      guidance: [],
      urgency: this.mapRiskStateToUrgency(context.risk.state),
      disclaimer: "AI Companion is currently unavailable. Sensor telemetry and risk indicators remain active and authoritative.",
      authoritativeState: {
        riskState: context.risk.state,
        overallRisk: context.risk.overall,
        dominantRisk: String(context.risk.dominantRisk),
        fallState: String(context.fall.state),
        fallAlertActive: context.fall.alertActive,
      },
      latencyMs,
      error: reason,
    };
  }

  private mapRiskStateToUrgency(riskState: string): LlmUrgency {
    switch (riskState) {
      case "CRITICAL":
      case "EMERGENCY":
        return "CRITICAL";
      case "WARNING":
        return "WARNING";
      case "WATCH":
        return "WATCH";
      default:
        return "NORMAL";
    }
  }

  /**
   * Construct concise system prompt instructions enforcing clinical safety invariants
   */
  private buildSystemPrompt(context: SamadhanHealthContext): string {
    return [
      "You are the Samadhan Health AI Companion, an explanatory and guidance assistant.",
      "INVARIANTS:",
      "1. You explain structured sensor evidence and risk metrics already computed by the hardware.",
      "2. Do NOT diagnose diseases or invent clinical certainty (use 'risk indicator', 'elevated pattern', 'wellness guidance').",
      `3. Authoritative Risk State: ${context.risk.state} (Overall: ${context.risk.overall ?? "N/A"}, Dominant: ${context.risk.dominantRisk}). You MUST NOT downgrade this or claim the user is fine when WARNING/CRITICAL.`,
      `4. Authoritative Fall State: ${context.fall.state}. If FALL_CONFIRMED, never deny or reinterpret the fall.`,
      "5. Respond with a helpful, clear, and reassuring explanation of the physiological pattern.",
    ].join("\n");
  }

  /**
   * Adapter: Format context into Modal request payload matching data['telemetry'] schema
   */
  private buildModalPayload(context: SamadhanHealthContext): Record<string, unknown> {
    const telemetryString = [
      `Current Vitals: Heart Rate ${context.current.heartRate ?? "N/A"} BPM, SpO2 ${context.current.spo2 ?? "N/A"}%, Skin/Ambient Temp ${context.current.temperature ?? "N/A"}°C, Humidity ${context.current.humidity ?? "N/A"}%.`,
      `Circadian Baseline: Heart Rate ${context.baseline.heartRate ?? "N/A"} BPM, SpO2 ${context.baseline.spo2 ?? "N/A"}%.`,
      `Risk Assessment: Tier ${context.risk.state}, Overall Risk ${context.risk.overall ?? "N/A"}, Dominant Factor: ${context.risk.dominantRisk}.`,
      `Motion/Fall: Activity ${context.current.activity}, Fall State ${context.fall.state}.`,
      context.evidence && context.evidence.length > 0 ? `Evidence Factors: ${context.evidence.join("; ")}.` : "",
      `User Question: ${context.userQuery || "What is my current health status and physiological pattern?"}`,
    ].filter(Boolean).join(" ");

    return {
      telemetry: telemetryString,
      contextVersion: context.contextVersion,
      prompt: this.buildSystemPrompt(context),
      query: context.userQuery || "Explain current physiological pattern and provide wellness guidance.",
      health_context: {
        current: context.current,
        baseline: context.baseline,
        risk: context.risk,
        fall: context.fall,
        evidence: context.evidence,
      },
      conversation_history: context.conversationHistory || [],
      apiKey: this.apiKey || undefined,
    };
  }

  /**
   * Parse and validate Modal output into strict SamadhanLlmResponse
   */
  private parseAndValidateResponse(
    raw: unknown,
    context: SamadhanHealthContext,
    latencyMs: number
  ): SamadhanLlmResponse {
    if (!raw || typeof raw !== "object") {
      throw new Error("Modal response is not a valid JSON object");
    }

    const res = raw as ModalRawResponse;

    // Support embedded JSON text or string wrapped outputs
    let parsed: Record<string, unknown> = res as Record<string, unknown>;
    if (typeof res.text === "string" || typeof res.response === "string" || typeof res.output === "string") {
      const textToParse = res.text || res.response || res.output || "";
      const jsonMatch = textToParse.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        try {
          parsed = JSON.parse(jsonMatch[0]);
        } catch {
          // Fall back to treating string as explanation
          parsed = { explanation: textToParse.slice(0, MAX_EXPLANATION_LENGTH) };
        }
      }
    }

    const explanation = typeof parsed.explanation === "string" ? parsed.explanation.trim() : "";
    if (!explanation) {
      throw new Error("Missing or empty explanation in LLM response");
    }

    const rawGuidance = Array.isArray(parsed.guidance)
      ? parsed.guidance
      : typeof parsed.guidance === "string"
      ? [parsed.guidance]
      : [];

    const guidance: string[] = rawGuidance
      .filter((g): g is string => typeof g === "string" && g.trim().length > 0)
      .slice(0, MAX_GUIDANCE_ITEMS)
      .map((g) => g.trim().slice(0, MAX_GUIDANCE_ITEM_LENGTH));

    const allowedUrgencies = new Set(["NORMAL", "WATCH", "WARNING", "CRITICAL"]);
    let urgency: LlmUrgency = typeof parsed.urgency === "string" && allowedUrgencies.has(parsed.urgency.toUpperCase())
      ? (parsed.urgency.toUpperCase() as LlmUrgency)
      : this.mapRiskStateToUrgency(context.risk.state);

    // SAFETY INVARIANT: LLM cannot downgrade deterministic WARNING or CRITICAL risk state
    const authoritativeUrgency = this.mapRiskStateToUrgency(context.risk.state);
    if (authoritativeUrgency === "CRITICAL" && urgency !== "CRITICAL") {
      urgency = "CRITICAL";
    } else if (authoritativeUrgency === "WARNING" && urgency === "NORMAL") {
      urgency = "WARNING";
    }

    const disclaimer = typeof parsed.disclaimer === "string" && parsed.disclaimer.trim().length > 0
      ? parsed.disclaimer.trim()
      : STANDARD_DISCLAIMER;

    return {
      status: "SUCCESS",
      explanation: explanation.slice(0, MAX_EXPLANATION_LENGTH),
      guidance,
      urgency,
      disclaimer,
      authoritativeState: {
        riskState: context.risk.state,
        overallRisk: context.risk.overall,
        dominantRisk: String(context.risk.dominantRisk),
        fallState: String(context.fall.state),
        fallAlertActive: context.fall.alertActive,
      },
      latencyMs,
    };
  }

  /**
   * Execute single HTTP request to Modal with timeout
   */
  private async dispatchModalRequest(
    payload: Record<string, unknown>,
    signal: AbortSignal
  ): Promise<{ status: number; data: unknown }> {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      "Accept": "application/json",
    };

    if (this.apiKey) {
      headers["Authorization"] = `Bearer ${this.apiKey}`;
      headers["x-api-key"] = this.apiKey;
    }

    const res = await fetch(this.apiUrl, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
      signal,
    });

    let data: unknown = null;
    try {
      data = await res.json();
    } catch {
      data = null;
    }

    return { status: res.status, data };
  }

  /**
   * Main Entry Point: Generate Explanation for Authoritative Health Context
   */
  async generateExplanation(context: SamadhanHealthContext): Promise<SamadhanLlmResponse> {
    const startTime = Date.now();
    console.log("[SamadhanLLM] Request started for context version:", context.contextVersion);

    const payload = this.buildModalPayload(context);

    // Attempt request with bounded timeout (8s) and at most 1 retry
    let lastError = "";
    for (let attempt = 1; attempt <= 2; attempt++) {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

      try {
        const { status, data } = await this.dispatchModalRequest(payload, controller.signal);
        clearTimeout(timer);

        const latencyMs = Date.now() - startTime;

        if (status === 200 && data) {
          try {
            const validated = this.parseAndValidateResponse(data, context, latencyMs);
            console.log(`[SamadhanLLM] Completed successfully in ${latencyMs}ms (attempt ${attempt})`);
            return validated;
          } catch (valErr) {
            console.warn(`[SamadhanLLM] Response validation rejected on attempt ${attempt}:`, (valErr as Error).message);
            lastError = "MALFORMED_RESPONSE";
            // Do not retry malformed response from live server
            break;
          }
        }

        console.warn(`[SamadhanLLM] Modal returned status ${status} on attempt ${attempt}`);
        lastError = `MODAL_HTTP_${status}`;

        // Do not retry 4xx client errors
        if (status >= 400 && status < 500) {
          break;
        }
      } catch (err: unknown) {
        clearTimeout(timer);
        const isAbort = (err as Error).name === "AbortError";
        lastError = isAbort ? "MODAL_TIMEOUT" : "MODAL_UNAVAILABLE";
        console.warn(`[SamadhanLLM] Attempt ${attempt} failed: ${lastError}`);

        if (attempt === 1) {
          // Brief pause before single retry
          await new Promise((r) => setTimeout(r, 400));
        }
      }
    }

    const totalLatency = Date.now() - startTime;
    console.warn(`[SamadhanLLM] Modal unavailable (${lastError || "NO_RESPONSE"}) after ${totalLatency}ms. Returning AI_ASSISTANT_UNAVAILABLE.`);
    return this.createFallbackResponse(context, lastError || "MODAL_UNAVAILABLE", totalLatency);
  }
}

export const samadhanLlmService = new SamadhanLlmService();
